server {
    # Enable TLS
    listen 443 ssl;
    server_name nginx-mldsa.mtc-demo.test localhost;

    # Limit to TLS 1.3 because only TLS 1.3 has PQC
    ssl_protocols TLSv1.3;

    # Specify the certificate and key to use
    ssl_certificate /etc/nginx/certs/leaf.crt;
    ssl_certificate_key /etc/nginx/certs/leaf.key;

    # There is no other relevant HTTPS configuration. We just specify the
    # certificate and the key, and rely on the OpenSSL backing this NGINX to
    # understand how to use an ML-DSA key.

    # ...but we should still make sure the demo server actually serves a little
    # content :)
    location / {
        default_type text/plain;
        return 200 "nginx-mldsa: ML-DSA certificate served by stock nginx:stable\n";
    }
}
