services:
  mtc-ca:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACTUS_REPOSITORY: https://github.com/dadrian/cactus.git
        CACTUS_REF: 682f9622c84108bf2e9c89aaa6788bfeaaa98b81
    image: mtc-demos/mtc-ca:latest
    container_name: mtc-ca
    hostname: mtc-ca
    ports:
      - "14000:14000"
      - "14080:14080"
      - "14090:14090"
    volumes:
      - ./state:/var/lib/cactus
    networks:
      mtc-demo:
        aliases:
          - mtc-ca
          - ca.mtc-demo.test

networks:
  mtc-demo:
    name: mtc-demo
